[telemetry]
hosts = [ "10.193.23.1" ]
url = "https://{0}:30443/gateway/default/webhdfs/v1/mtool"

[pansop]
framework_location = "~/src/aris_1/projects/pansop" 
libraries = [   "~/src/aris_1/projects/pansop/output/bdc",
                "~/src/pm-tools_1/aris-tests/pansop-lib/aris",
                "~/src/pm-tools_1/aris-tests/pansop-lib/sqlpal",
                "~/src/meta_1/infra/dogfood/pansop-lib/output/latest/library/df" ]